# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "36697cd6da14321ce7a4f40b9f1a335e"
name = "task-1"
handle = "task-24"
application_url = "https://ac-predict-borders-wyoming.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ac-predict-borders-wyoming.trycloudflare.com/auth/callback",
  "https://ac-predict-borders-wyoming.trycloudflare.com/auth/shopify/callback",
  "https://ac-predict-borders-wyoming.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "test-store-tasks.myshopify.com"
automatically_update_urls_on_dev = true
